name: flutter_gemini_ai
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.1
  flutter_markdown: ^0.7.1
  google_generative_ai: ^0.4.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
